# Generated by Django 5.2.6 on 2025-09-17 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('politica', 'Política'), ('esportes', 'Esportes'), ('tecnologia', 'Tecnologia'), ('entretenimento', 'Entretenimento')], max_length=50)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['noticia', 'usuario'], name='noticias_vo_noticia_aed5fa_idx')],
                'unique_together': {('noticia', 'usuario')},
            },
        ),
    ]
