# Generated by Django 5.2.6 on 2025-09-22 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='salvo_por',
            field=models.ManyToManyField(blank=True, related_name='noticias_salvas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
