# Generated by Django 5.2.5 on 2025-09-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voto',
            name='noticias_vo_noticia_aed5fa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'noticia')},
        ),
        migrations.AddField(
            model_name='noticia',
            name='salvo_por',
            field=models.ManyToManyField(blank=True, related_name='noticias_salvas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voto',
            name='valor',
            field=models.SmallIntegerField(choices=[(1, 'Bom'), (-1, 'Ruim')]),
        ),
        migrations.RemoveField(
            model_name='voto',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='criado_em',
        ),
    ]
