# Generated by Django 5.2.6 on 2025-09-24 20:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_voto_noticias_vo_noticia_aed5fa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Salvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='salvo_por',
        ),
        migrations.AddField(
            model_name='noticia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 24, 20, 48, 50, 851635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='legenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 24, 20, 49, 14, 395642, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('noticia', 'usuario'), name='unique_user_vote_per_news'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='assuntos',
            field=models.ManyToManyField(blank=True, related_name='noticias', to='noticias.assunto'),
        ),
        migrations.AddField(
            model_name='salvo',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia'),
        ),
        migrations.AddField(
            model_name='salvo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='salvos',
            field=models.ManyToManyField(blank=True, related_name='noticias_salvas', through='noticias.Salvo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salvo',
            unique_together={('usuario', 'noticia')},
        ),
    ]
