# Generated by Django 5.2.6 on 2025-09-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_assunto_salvo_alter_voto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_rel', to='noticias.noticia'),
        ),
    ]
