# Generated by Django 5.2.6 on 2025-09-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_voto_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='noticias.noticia'),
        ),
    ]
