# Generated by Django 5.2.7 on 2025-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_voto_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
