name: CI/CD Django app to Azure Web App - Brasa

on:
  push:
    branches:
      - prod 
  workflow_dispatch:

jobs:
  # --- JOB 1: TESTAR (CI) ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          SECRET_KEY: "dummy-key-para-testes"
          GEMINI_API_KEY: "dummy-gemini-key-para-testes"
        run: python manage.py test

  # --- JOB 2: CONSTRUIR (BUILD) ---
  build:
    needs: test 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run collectstatic
        run: python manage.py collectstatic --noinput
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" "__pycache__/*" ".git*" "db.sqlite3*"
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: release.zip

  # --- JOB 3: IMPLANTAR (DEPLOY) ---
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Brasa'