name: Deploy Django app to Azure Web App - projetoBrasa

on:
  push:
    branches:
      - prod 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Baixa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Coleta arquivos estáticos
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      # Aplica migrações (opcional)
      - name: Run migrations
        run: python manage.py migrate

      # Cria o pacote para envio ao Azure
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" "__pycache__/*"

      # Envia o pacote para o próximo job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      # Baixa o pacote gerado no job anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      # Descompacta o pacote
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Faz login no Azure com os segredos configurados
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # Faz o deploy no Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'projetoBrasa'
